In [1]:
import numpy as np

In [14]:
a = np.array([5,6,7,8])

In [15]:
print(a)

[5 6 7 8]


In [16]:
a[0]

5

In [17]:
a[1]

6

In [18]:
a.ndim

1

In [19]:
b = np.array([[1,2], [2,3], [3,4], [4,5]])

In [20]:
b.ndim

2

In [21]:
b[0]

array([1, 2])

In [22]:
a.itemsize

4

In [23]:
b.itemsize

4

In [25]:
a.size

4

In [26]:
b.size

8

In [27]:
a.shape

(4,)

In [28]:
b.shape

(4, 2)

In [29]:
np.zeros([2,3])

array([[0., 0., 0.],
       [0., 0., 0.]])

In [31]:
np.ones([2,3])

array([[1., 1., 1.],
       [1., 1., 1.]])

In [32]:
np.arange(1,7)

array([1, 2, 3, 4, 5, 6])

In [33]:
np.linspace(1,5,20)

array([1.        , 1.21052632, 1.42105263, 1.63157895, 1.84210526,
       2.05263158, 2.26315789, 2.47368421, 2.68421053, 2.89473684,
       3.10526316, 3.31578947, 3.52631579, 3.73684211, 3.94736842,
       4.15789474, 4.36842105, 4.57894737, 4.78947368, 5.        ])

In [36]:
b.shape

(4, 2)

In [41]:
b.reshape(2,4)

array([[1, 2, 2, 3],
       [3, 4, 4, 5]])

In [42]:
b.reshape(8,1)

array([[1],
       [2],
       [2],
       [3],
       [3],
       [4],
       [4],
       [5]])

In [43]:
b.ravel()

array([1, 2, 2, 3, 3, 4, 4, 5])

In [45]:
b.min()

1

In [46]:
b.max()

5

In [47]:
b.sum()

24

In [48]:
b

array([[1, 2],
       [2, 3],
       [3, 4],
       [4, 5]])

In [50]:
b.sum(axis=0)

array([10, 14])

In [51]:
np.sqrt(b)

array([[1.        , 1.41421356],
       [1.41421356, 1.73205081],
       [1.73205081, 2.        ],
       [2.        , 2.23606798]])

In [52]:
np.std(b)

1.224744871391589

In [53]:
c = np.array([[1,2], [3,4]])

In [54]:
d = np.array([[5,6], [7,8]])

In [55]:
c

array([[1, 2],
       [3, 4]])

In [56]:
d

array([[5, 6],
       [7, 8]])

In [57]:
c+d

array([[ 6,  8],
       [10, 12]])

In [59]:
c*d

array([[ 5, 12],
       [21, 32]])

In [60]:
c/d

array([[0.2       , 0.33333333],
       [0.42857143, 0.5       ]])

In [61]:
c.dot(d)

array([[19, 22],
       [43, 50]])